### ISSUE TITLE
Question on GPUMonitor results.

### ISSUE THREAD

**Issue by LarsBeentjes** [LarsBeentjes/GPUScheduling#10]
https://github.com/LarsBeentjes/GPUScheduling/blob/9923890bd026f7d99462283608720561ba04d889/monitor/GPUMonitor.py

result['used_memory'] = process_info.find('used_memory').text
result['memory_usage'] = gpu.find('fb_memory_usage').find('used').text
result['memory_total'] = gpu.find('fb_memory_usage').find('total').text
result['gpu_utilization'] = gpu.find('utilization').find('gpu_util').text
result['mem_utilization'] =  gpu.find('utilization').find('memory_util').text

What do these things give me, exactly? I.e. integers (prob?), and what do those values indicate, exactly?

**Comment by elgarvdzande** [comment]
De eerste is de het aantal geheuegen dat een process gebruikt
tweede is het aantal geheugen dat in gebruik is op een bepaalde kaart
de 3e is het totaal aantal geheugen op de kaart
utilization is het het gebruik van de GPU of wel percentage tussen 0% en 100%
memory utils is als het goed ook gewoon het percentage van het gebruikte geheugen

**Comment by LarsBeentjes** [comment]
Ah, thanks, but in exact numbers? I.e. do number 1, 2 and 3 give me the amount of bits, bytes, doublewords, KB, MB, GB? And for the very first, that's the memory use right at the current moment, right? Not historical memory use?
Not sure how I'm supposed to be implementing 'has been idling for X amount of time' rules is all.

**Comment by elgarvdzande** [comment]
De eenheid zit in de het text veld, dus als je er echt iets mee van plan bent, helaas. Maar dat lijkt me niet nodig.
Voor idle detectie lijkt het volgende me wel een oplossing:
```
for proc in processes:
    if proc['utilization'] < 5.0 and proc['age'] > 600.0:
        handle_idle_process(proc)
```

echter, hiermee worden ook processen bestraft die toevallig even niets staan te doen. Een andere dus misschien is het handig om bij te houden of het process de vorige N polls ook als stond te idle'en, en als dat het geval is kan je een actie onder nemen.

Een ander probleen dat zich voordoet is natuurlijk dat er een primaire key nodig is van een process dat staat te idle'en. Als je zo'n lijstje bij gaat houden.

P.S. ik weet niet precies of die indices in de pseudo code echt bestaan, maar iets soorstgelijks is wel beschikbaar.

**Comment by LarsBeentjes** [comment]
Ik heb een regelbouwer ding, het moet toch zijn 'how long idle', niet 'if idle', dus da's goed.
Het is correct dat er maar een proces per GPU per keer is, ja? Dat heb ik me niet verkeerd herinnert?

**Comment by elgarvdzande** [comment]
"Het is correct dat er maar een proces per GPU per keer is, ja?" ja klopt anders zou het ook niet echt te detecteren zijn, want kennelijk is het niet mogelijk op te halen hoeveel een process aan het uitvreten is op een GPU.
