### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by LarsBeentjes** [LarsBeentjes/GPUScheduling#13]
https://github.com/LarsBeentjes/GPUScheduling/blob/6290d6de4754a97197343f3d8236ff245ad65364/GPU_monitor_Doc.tex#L48

Also others. Not doing it _again_.

**Comment by LarsBeentjes** [comment]
Mainly, Gilles.

**Comment by LarsBeentjes** [comment]
This probably comes across as rude. Sorry about that, don't mean it that way. Spellcheck is still necessary though.

**Comment by Ottervanger** [comment]
ja soorry, had per ongeluk de oude versie aangepast...
ik dacht echter dat het inmiddels gelukt was de goede versie te uploaden 5 commits verder, maar ik faal

**Comment by Ottervanger** [comment]
OK nu zou hij goed moetn zijn
