### ISSUE TITLE
Overbodige functie

### ISSUE THREAD

**Issue by elgarvdzande** [LarsBeentjes/GPUScheduling#3]
https://github.com/LarsBeentjes/GPUScheduling/blob/5f6cc3375004de74879dae67f09044476b131682/Mailer/Mailer.py#L54

Deze functie lijkt mij eerlijk gezegd niet zo handig, want volgens mij vervangt hij alleen maar een bepaald stukje string met een naam. Dat kan in princiepe ook wel met text.replace('[...]', name). Verder lijken mij deze globals niet zo handig/duidelijk:
replacements = ['[USERNAME]', '[SERVERNUM]']
helpthings = ['', '']

**Comment by LarsBeentjes** [comment]
Fixed, thanks. I keep forgetting utility functions like that. Changed array names, but they're there so we have a more central place to have things that are to be replaced than a whole list of 				mailsubject = mailsubject.replace([EXAMPLE], str(example))			
mailbody = mailbody.replace([EXAMPLE], str(example)) 				
mailsubject = mailsubject.replace([EXAMPLE2], str(example2))			
mailbody = mailbody.replace([EXAMPLE2], str(example2)) 				
mailsubject = mailsubject.replace([EXAMPLE3], str(example3))			
mailbody = mailbody.replace([EXAMPLE3], str(example3))
Etc. Now it can be done neatly with for-loops.
I tried to do that with the arguments we get directly too, but couldn't figure out how to iterate a for-loop over them. Testing a bit right now.
Edit: Yeah, screw that, it's all way overcomplicated. This is just fine.

**Comment by elgarvdzande** [comment]
Je zou een array kunnen maken met paren eg.
```
replacements = [['[USERNAME]', username], ['[SERVERNUM]', servernum]]
```
daar kan je dan op de volgende manier door heen:
```
for match, replacement in replacements:
    # code
```

**Comment by elgarvdzande** [comment]
of je kan ```zip``` gebruiken
