### ISSUE TITLE
continue > break

### ISSUE THREAD

**Issue by elgarvdzande** [LarsBeentjes/GPUScheduling#5]
https://github.com/LarsBeentjes/GPUScheduling/blob/8fe24e8bf43bfd15d22f5f4a2176a4b394b02b28/Mailer/Mailer.py#L62

contine is hier handiger, als iemand bijvoorbeeld een lege regel er tussen laat stop de loop. Dus worden er geen volgende adressen meer gecheckt.

**Comment by LarsBeentjes** [comment]
done
