### ISSUE TITLE
Hardcoded thingy

### ISSUE THREAD

**Issue by LarsBeentjes** [LarsBeentjes/GPUScheduling#7]
https://github.com/LarsBeentjes/GPUScheduling/blob/f2df2dcd2cdd11f952264f953de2e5d361b40af0/Mailer/Mail_Controller.py#L32

This looks like a hardcoded thingy and that needs to be fixed, but not sure how. Someone?

**Comment by elgarvdzande** [comment]
ja klopt maar dat regelen we wel even als we een account hebben om dat ding in te draaien.
