### ISSUE TITLE
Needs testing

### ISSUE THREAD

**Issue by LarsBeentjes** [LarsBeentjes/GPUScheduling#8]
https://github.com/LarsBeentjes/GPUScheduling/blob/2459f03d1bc33815467dad042a020a8ea0944143/Mailer/Mail_Controller.py

Somebody who knows how to work the rest of this thing on the duranium test if the rules system works. The readme is fairly clear, I think, but ask questions if you have to.

**Comment by LarsBeentjes** [comment]
If you're testing already, I fixed a bug with isinstance(helptext[0], int) always returning false, because it's a string.

**Comment by elgarvdzande** [comment]
opgelost
