### ISSUE TITLE
Path

### ISSUE THREAD

**Issue by lucmans** [LarsBeentjes/GPUScheduling#9]
https://github.com/LarsBeentjes/GPUScheduling/blob/2459f03d1bc33815467dad042a020a8ea0944143/Mailer/Mail_Controller.py#L10

Je kan ook os.getcwd() (als je "import os" hebt gedaan) gebruiken om de current working directory te krijgen.

**Comment by LarsBeentjes** [comment]
Werkt niet, als het huidige working directory werkte dan zou dit sowieso niet nodig zijn. Het probleem is dat het working directory niet de directory van de mailcontroller en mailer zelf hoeft te zijn, dus die moet ik op een andere manier krijgen, dat is sys.path[0]

**Comment by lucmans** [comment]
Sorry, ik dacht dat je iets anders bedoelde met de comment. Ik zie nu dat het klopt.
